test and fix datalake sample config

diff --git a/bin/mdaa b/bin/mdaa
--- a/bin/mdaa
+++ b/bin/mdaa
@@ -9,8 +9,17 @@ echo ""
 echo "Building MDAA CLI"
 echo ""
 npx lerna run build --scope "@aws-mdaa/cli" --loglevel warn > /dev/null
-echo "Installing Python Packages"
-pip install -q -r requirements.txt
+
+echo ""
+echo "Checking for pip availability..."
+which pip
+if [[ $? -eq 0 ]]; then
+    echo "Installing Python Packages with Pip"
+    pip install -q -r requirements.txt
+else
+    echo "Pip not found. Skipping Python package installation. Terraform functionality might be limited."
+fi
+
 echo ""
 cd "$cwd"
 "$parent_path/../packages/cli/bin/mdaa" $@
